### ISSUE TITLE
BART Runner crashes in airplane mode

### ISSUE THREAD

**Issue by bdcgoogle** [dougkeen/BartRunnerAndroid#16]
=====STEPS TO REPRODUCE=====
1. enter airplane mode
2. open bart runner app
3. tap quick departure lookup at bottom of screen, choose an origin and destination, hit ok

EXPECTED RESULTS:
I'm actually not sure if it has cached offline data or is supposed to pop up an error message of some sort

NUMBER OF TIMES YOU WERE ABLE TO REPRODUCE (e.g. 3/10): 10/10

DEVICES TESTED: Nexus 5X Android O preview, Pixel Android N

Issue is 100% reproducible with airplane mode.

Build: sailfish-userdebug 7.1.2 N2G48C 4104010 dev-keys

Package [com.dougkeen.bart] (a4f88e8):
    versionCode=37 minSdk=14 targetSdk=25
    versionName=2.2.10

java.lang.RuntimeException: An error occurred while executing doInBackground()
GMS RETRACE
  at android.os.AsyncTask$3.done(AsyncTask.java:325)
  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
  at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
  at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.NullPointerException: application interceptor com.dougkeen.bart.networktasks.NetworkUtils$RetryInterceptor@3c77394 returned null
GMS RETRACE
  at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:235)
  at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
  at com.squareup.okhttp.Call.execute(Call.java:80)
  at com.dougkeen.bart.networktasks.GetRealTimeDeparturesTask.getDeparturesFromNetwork(GetRealTimeDeparturesTask.java:94)
  at com.dougkeen.bart.networktasks.GetRealTimeDeparturesTask.doInBackground(GetRealTimeDeparturesTask.java:65)
  at com.dougkeen.bart.networktasks.GetRealTimeDeparturesTask.doInBackground(GetRealTimeDeparturesTask.java:20)
  at android.os.AsyncTask$2.call(AsyncTask.java:305)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)

**Comment by dougkeen** [comment]
Thanks for the report. Repro'd on my Nexus 6p. I'll take a look as soon as I can (unless some other contributor beats me to it... should be a fairly simple fix)

**Comment by dougkeen** [comment]
Fixed in latest release
