### ISSUE TITLE
The application crashes suddenly after selecting departures.

### ISSUE THREAD

**Issue by sargoon** [dougkeen/BartRunnerAndroid#28]
Hi @dougkeen 

**Expected behavior**

The BART Runner users need to be able to use Favorite Routes -> Selecting any Departures action on this application.

**Actual behavior**

Firstly, I have chosen any route from **Favorite Routes** section, then I clicked on any **Departures**, The application crashes suddenly after selecting departures.

**How to reproduce**

1. Open the BART Runner app.
2. Click on the any Favorite Route.
3. Then click on any Departures option.
4. And you will see that the application crashes suddenly.

• App version: 2.2.17 (latest)
• Operating system: Android 9.0

**Recording Of The Bug**
![bug](https://user-images.githubusercontent.com/34961616/60369853-a1182300-99fd-11e9-9441-f26e6f99204e.gif)

**Logcat Report**
`java.lang.SecurityException: Permission Denial: startForeground from pid=31105, uid=10184 requires android.permission.FOREGROUND_SERVICE
	at android.os.Parcel.createException(Parcel.java:1953)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5144)
	at android.app.Service.startForeground(Service.java:695)
	at com.dougkeen.bart.services.BoardedDepartureService.updateNotification(BoardedDepartureService.java:327)
	at com.dougkeen.bart.services.BoardedDepartureService.onHandleIntent(BoardedDepartureService.java:202)
	at com.dougkeen.bart.services.BoardedDepartureService$ServiceHandler.handleMessage(BoardedDepartureService.java:66)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:9573)
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1226)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:901)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:21069)
	at android.app.IActivityManager$Stub.onTransact$setServiceForeground$(IActivityManager.java:10581)`

**Comment by dougkeen** [comment]
That's strange, because `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />` is definitely in the manifest.

Are you sure you're running the latest version (2.2.18)?

**Comment by sargoon** [comment]
> 
> 
> That's strange, because `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />` is definitely in the manifest.
> 
> Are you sure you're running the latest version (2.2.18)?

I downloaded this application via F-Droid and saw that the latest version is 2.2.17. Where can I access the latest version?

**Comment by sargoon** [comment]
By the way, doesn't this count as an bug?

**Comment by sargoon** [comment]
And I did a little research for version 2.2.18 but couldn't find it.
![WhatsApp Image 2019-06-29 at 12 32 30 AM](https://user-images.githubusercontent.com/34961616/60372561-9f525d80-9a05-11e9-9031-7edb1781ee47.jpeg)

**Comment by dougkeen** [comment]
Ah, looks like I forgot to tag the latest release. I just pushed a new tag for 2.2.18, which I _think_ should trigger a new build on F-Droid. Let me know if you still see the issue with the new build (or if the new build never arrives).

**Comment by sargoon** [comment]
> 
> 
> Ah, looks like I forgot to tag the latest release. I just pushed a new tag for 2.2.18, which I _think_ should trigger a new build on F-Droid. Let me know if you still see the issue with the new build (or if the new build never arrives).

Thank you so much for your reply! Checking. I'll let you know immediately.

**Comment by sargoon** [comment]
I couldn't find the apk file in the .zip/.tar.gz files of the new version.

**Comment by dougkeen** [comment]
Looks like F-Droid [hasn't build the newest version yet](https://f-droid.org/wiki/page/Category:Apps_to_Update). Apparently, [it can take a day or longer](https://f-droid.org/en/docs/FAQ_-_App_Developers/#ive-published-a-new-release-why-is-it-not-in-the-repository).

**Comment by sargoon** [comment]
Well, see you again when the new version is installed on F-Droid!

**Comment by bwitt** [comment]
f-droid has the latest version now (2.2.18) at https://f-droid.org/packages/com.dougkeen.bart/ , and it doesn't crash for me on that version.
