### ISSUE TITLE
Crashes on Marshmallow

### ISSUE THREAD

**Issue by dougkeen** [dougkeen/BartRunnerAndroid#8]
Received several reports of crashing. Looks related to ActionBarSherlock/HoloEverywhere:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dougkeen.bart/com.dougkeen.bart.activities.RoutesListActivity_}: java.lang.RuntimeException: java.lang.IllegalAccessException: java.lang.Class<org.holoeverywhere.addon.AddonSherlock$HoloActionBarSherlockNative> is not accessible from java.lang.Class<com.actionbarsherlock.ActionBarSherlock>
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: java.lang.Class<org.holoeverywhere.addon.AddonSherlock$HoloActionBarSherlockNative> is not accessible from java.lang.Class<com.actionbarsherlock.ActionBarSherlock>
	at com.actionbarsherlock.ActionBarSherlock.wrap(ActionBarSherlock.java:239)
	at org.holoeverywhere.addon.AddonSherlock$AddonSherlockA.getSherlock(AddonSherlock.java:53)
	at org.holoeverywhere.addon.AddonSherlock$AddonSherlockA.installDecorView(AddonSherlock.java:60)
	at android.support.v4.app._HoloActivity$1.action(_HoloActivity.java:587)
	at android.support.v4.app._HoloActivity$1.action(_HoloActivity.java:1)
	at org.holoeverywhere.addon.IAddonBasicAttacher.performAddonAction(IAddonBasicAttacher.java:167)
	at org.holoeverywhere.app.Activity.performAddonAction(Activity.java:497)
	at android.support.v4.app._HoloActivity.requestDecorView(_HoloActivity.java:584)
	at android.support.v4.app._HoloActivity.setContentView(_HoloActivity.java:604)
	at com.dougkeen.bart.activities.RoutesListActivity_.setContentView(RoutesListActivity_.java:107)
	at com.dougkeen.bart.activities.RoutesListActivity_.onCreate(RoutesListActivity_.java:42)
	at android.app.Activity.performCreate(Activity.java:6237)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
	... 9 more
Caused by: java.lang.IllegalAccessException: java.lang.Class<org.holoeverywhere.addon.AddonSherlock$HoloActionBarSherlockNative> is not accessible from java.lang.Class<com.actionbarsherlock.ActionBarSherlock>
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at com.actionbarsherlock.ActionBarSherlock.wrap(ActionBarSherlock.java:231)
	... 22 more
```

**Comment by psg190** [comment]
Thanks for flagging.

**Comment by sevenwong** [comment]
what `s the reason of this crashes,and how do you fix it .i had get the same problem.thanks

**Comment by dougkeen** [comment]
Iirc, it was just an ActionbarSherlock compatibility problem. Getting rid of the lib fixed it.
